spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/mspayments}
    username: ${DATABASE_USERNAME:mspayments}
    password: ${DATABASE_PASSWORD:1234567}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

ms:
  events:
    registration:
      url: ${MSEVENTSREGISTRATION_URL:http://localhost:50054}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security: DEBUG